import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import styles from "./layout.module.css";

import NavBar from "./components/navbar";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resolvo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${styles.body} ${rubik.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
